version: "3.9"
services:
  api:
    container_name: unified-api-server
    build: .
    ports:
      - "5000:5000"
  redis:
    image: redis
    container_name: redis-container
    ports:
       - "6379:6379"  
    env_file:
       - .flaskenv
       - .env
    volumes:
      - .:/api       
 